# Generated by Django 4.2.7 on 2024-09-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ManyToManyField(blank=True, to='blog.blogimage'),
        ),
    ]
